const characterImages = {
    "GG": "Images/Character Avatars/GG.png",
    "Security": "Images/Character Avatars/guard.png",
    "girlfriend": "",
    "Stranger": "Images/Character Avatars/jin.png",
    "Wanderer": "Images/Character Avatars/jin.png",
    "Taxi_driver": "Images/Character Avatars/jin.png",
    "#boyname": "",
    "Tree": "",
    "DarkFavn": "Images/Character Avatars/faun.png",
    "Favn": "Images/Character Avatars/faun.png",
    "Innkeeper": "Images/Character Avatars/innkeeper.png",
    "tot_outline": "",
    "totem": "",
    "totem_nn": "",
    "dark_spider": "Images/Character Avatars/spider1.png",
    "spider": "Images/Character Avatars/spider1.png",
    "dealer_dark": "",
    "spider2": "Images/Character Avatars/spider2.png",
    "spider3": "Images/Character Avatars/spider3.png",
    "dealer": "",
    "Boyfriend": "",
    "voice_ch3": "",
    "witch": "Images/Character Avatars/witch.png",
    "shadow": "",
    "Centaur": "",
    "dryad": "",
    "Siu": "Images/Character Avatars/sui.png",
    "witch3": "Images/Character Avatars/witch.png",
    "witch2": "Images/Character Avatars/witch.png",
    "SiuReal": "evil_sui.png",
    "tot_voice": "",
};