const characterImages = {
    "GG": "Images/Character Avatars/test.jpg",
    "Security": "",
    "girlfriend": "",
    "Stranger": "",
    "Wanderer": "",
    "Taxi_driver": "",
    "#boyname": "",
    "Tree": "",
    "DarkFavn": "",
    "Favn": "",
    "Innkeeper": "",
    "tot_outline": "",
    "totem": "",
    "totem_nn": "",
    "dark_spider": "",
    "spider": "",
    "dealer_dark": "",
    "spider2": "",
    "spider3": "",
    "dealer": "",
    "Boyfriend": "",
    "voice_ch3": "",
    "witch": "",
    "shadow": "",
    "Centaur": "",
    "dryad": "",
    "Siu": "",
    "witch3": "",
    "witch2": "",
    "SiuReal": "",
    "tot_voice": "",
};