const characterImages = {
    "GG": "Images/Character Avatars/GG.png",
    "Security": "Images/Character Avatars/guard.png",
    "girlfriend": "Images/placeholder.png",
    "Stranger": "Images/Character Avatars/jin.png",
    "Wanderer": "Images/Character Avatars/jin.png",
    "Taxi_driver": "Images/Character Avatars/jin.png",
    "#boyname": "Images/placeholder.png",
    "Tree": "Images/placeholder.png",
    "DarkFavn": "Images/Character Avatars/faun.png",
    "Favn": "Images/Character Avatars/faun.png",
    "Innkeeper": "Images/Character Avatars/innkeeper.png",
    "tot_outline": "Images/placeholder.png",
    "totem": "Images/placeholder.png",
    "totem_nn": "Images/placeholder.png",
    "dark_spider": "Images/Character Avatars/spider1.png",
    "spider": "Images/Character Avatars/spider1.png",
    "dealer_dark": "Images/placeholder.png",
    "spider2": "Images/Character Avatars/spider2.png",
    "spider3": "Images/Character Avatars/spider3.png",
    "dealer": "Images/placeholder.png",
    "Boyfriend": "Images/placeholder.png",
    "voice_ch3": "Images/placeholder.png",
    "witch": "Images/Character Avatars/witch.png",
    "shadow": "Images/placeholder.png",
    "Centaur": "Images/placeholder.png",
    "dryad": "Images/placeholder.png",
    "Siu": "Images/Character Avatars/sui.png",
    "witch3": "Images/Character Avatars/witch.png",
    "witch2": "Images/Character Avatars/witch.png",
    "SiuReal": "evil_sui.png",
    "tot_voice": "Images/placeholder.png",
};