const frameTypes = new Map();
frameTypes.set("Animation", '#00FBCE');
frameTypes.set("Bubble", '#FBE200');
frameTypes.set("Choice", '#ffa14a');
frameTypes.set("Choice-by-choice", '#ff4a54');
frameTypes.set("Choice-by-character", '#ff4a54');
frameTypes.set("Customize", '#DA0C81');
frameTypes.set("Dialog", '#4aff67');
frameTypes.set("Item", '#FBE200');
frameTypes.set("Item-check", '#ff4a54');
frameTypes.set("Love", '#FBE200');
frameTypes.set("Option", '#ffa14a');
frameTypes.set("Text", '#4aff67');
